### ISSUE TITLE
Error spamming logs [IndexOutOfBoundsException]

### ISSUE THREAD

**Issue by QORTEC** [Vectron/mapwriter#11]
The following error is spamming my logs/console:
````
java.lang.IndexOutOfBoundsException
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(RandomAccessFile.java:377)
	at javax.imageio.stream.FileImageInputStream.read(FileImageInputStream.java:117)
	at com.sun.imageio.plugins.common.SubImageInputStream.read(SubImageInputStream.java:61)
	at com.sun.imageio.plugins.common.InputStreamAdapter.read(InputStreamAdapter.java:47)
	at java.io.SequenceInputStream.read(SequenceInputStream.java:207)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1104)
	at com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1215)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1330)
	at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1606)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at mapwriter.region.SurfacePixels.loadImage(SurfacePixels.java:141)
	at mapwriter.region.SurfacePixels.load(SurfacePixels.java:46)
	at mapwriter.region.SurfacePixels.getPixels(SurfacePixels.java:65)
	at mapwriter.region.SurfacePixels.getOrAllocatePixels(SurfacePixels.java:71)
	at mapwriter.region.SurfacePixels.updateScaled(SurfacePixels.java:115)
	at mapwriter.region.Region.updateNextZoomLevel(Region.java:143)
	at mapwriter.region.Region.updateZoomLevels(Region.java:155)
	at mapwriter.region.SurfacePixels.updateChunk(SurfacePixels.java:91)
	at mapwriter.region.Region.updateChunk(Region.java:166)
	at mapwriter.region.RegionManager.updateChunk(RegionManager.java:123)
	at mapwriter.tasks.UpdateSurfaceChunksTask.run(UpdateSurfaceChunksTask.java:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

This bug is also present in "mapwriter 1":
daveyliam/mapwriter#33

**Versions**:
Forge: 10.13.4.1448
MapWriter: 2.1.9

**Comment by Vectron** [comment]
i cant explain this bug.

My best guess is update your java and other libraries. as far as i can see from the stacktrace something strange happens in a java library

**Comment by QORTEC** [comment]
I am using the most current stable release of Oracle Java.
I will try figuring out how to update the libraries to see if I can fix this issue.

**Versions**:
Java version: 1.8.0_60

**Comment by Vectron** [comment]
The libraries come packed with Java, so best bet is uninstalli g Java and reinstalling it.

It might also be something with Ubuntu but i have no expirience on that.

Dus this starten to happen after soms time or as soon as you installed the mod?

**Comment by Vectron** [comment]
closing this, no more feedback. and doesnt realy seem to be a bug with the mod but something outside not behaving

**Comment by Flamerion** [comment]
I know this is old but if someone else is also having this problems it seems to be related to the fact that the map can't read the image files in \saves\mapwriter_sp_worlds\"Your World"\images\, there you'll find some folders (DIM-1, z0, z1, z2), one of those is causing the problem ( mine was z1), note that once you delete the folder, all the map data of that folder (the surface/underground image) will be gone, and you'll have to re-explore this zone, but it's better than having this problem.
