### ISSUE TITLE
Errors on stop: Thermal Dynamics

### ISSUE THREAD

**Issue by QORTEC** [Vectron/mapwriter#12]
I am getting the following errors when I "Save and Quit" my single player game.

**Short**:
````
[13:45:27] [pool-10-thread-1/ERROR] [FML/]: A TileEntity type cofh.thermaldynamics.duct.fluid.TileFluidDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b([LP|ASM] TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.func_145841_b(TileFluidDuct.java:384) ~[TileFluidDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

[13:45:27] [pool-10-thread-1/ERROR] [FML/]: A TileEntity type cofh.thermaldynamics.duct.item.TileItemDuct has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at cofh.thermaldynamics.duct.attachments.ConnectionBase.writeToNBT(ConnectionBase.java:63) ~[ConnectionBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoBase.writeToNBT(ServoBase.java:53) ~[ServoBase.class:?]
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.writeToNBT(ServoItem.java:59) ~[ServoItem.class:?]
	at cofh.thermaldynamics.block.TileTDBase.func_145841_b([LP|ASM] TileTDBase.java:716) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.func_145841_b(TileItemDuct.java:477) ~[TileItemDuct.class:?]
	at mapwriter.region.MwChunk.writeChunkToNBT(MwChunk.java:366) [MwChunk.class:?]
	at mapwriter.region.MwChunk.write(MwChunk.java:399) [MwChunk.class:?]
	at mapwriter.tasks.SaveChunkTask.run(SaveChunkTask.java:17) [SaveChunkTask.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
````

**Longer**:
https://gist.github.com/QORTEC/92663fc02207b3903ff2

**Comment by Vectron** [comment]
the error in itself isnt a real problem,
i will see if i can fix it or else make sure it doesnt spam the log.
