### ISSUE TITLE
1.9 crashes on start

### ISSUE THREAD

**Issue by Mrtenz** [Vectron/mapwriter#27]
java.lang.NoSuchMethodError: net.minecraftforge.client.event.GuiOpenEvent.getGui()Lnet/minecraft/client/gui/GuiScreen;
	at mapwriter.forge.EventHandler.onGuiOpenEvent(EventHandler.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_EventHandler_onGuiOpenEvent_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:924)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:523)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Latest version of MapWriter

**Comment by Vectron** [comment]
Update to latest version of forge.

**Comment by Mrtenz** [comment]
That fixed it.
