### ISSUE TITLE
Chash with optifne

### ISSUE THREAD

**Issue by chief-j** [Vectron/mapwriter#44]
I suspect that conflict with OptiFine, because without game start normally
```java
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 15.07.16 10:58
Description: Initializing game

java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at mapwriter.util.Utils.allocateDirectIntBuffer(Utils.java:112)
	at mapwriter.util.Texture.<init>(Texture.java:54)
	at mapwriter.BlockColourGen.genBlockColours(BlockColourGen.java:97)
	at mapwriter.Mw.reloadBlockColours(Mw.java:289)
	at mapwriter.forge.EventHandler.onGuiOpenEvent(EventHandler.java:151)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventHandler_onGuiOpenEvent_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:931)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:530)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at mapwriter.util.Utils.allocateDirectIntBuffer(Utils.java:112)
	at mapwriter.util.Texture.<init>(Texture.java:54)
	at mapwriter.BlockColourGen.genBlockColours(BlockColourGen.java:97)
	at mapwriter.Mw.reloadBlockColours(Mw.java:289)
	at mapwriter.forge.EventHandler.onGuiOpenEvent(EventHandler.java:151)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventHandler_onGuiOpenEvent_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:931)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:530)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 316365976 bytes (301 MB) / 551550976 bytes (526 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2013 Optifine OptiFine_1.10.2_HD_U_C2 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2013.jar) 
	UCHIJA	Forge{12.18.1.2013} [Minecraft Forge] (forge-1.10.2-12.18.1.2013.jar) 
	UCHIJA	BetterHorseHud{1.0} [Better Horse Hud] (BetterHorseHud-[1.9-1.10.2]-1.0.jar) 
	UCHIJA	inventory_x{1.10-1.0.1} [Inventory X] (inventory_x-1.10-1.0.1.jar) 
	UCHIJA	JEI{3.7.5.227} [Just Enough Items] (jei_1.10.2-3.7.5.227.jar) 
	UCHIJA	MapWriter{2.6.19} [MapWriter] (MapWriter-1.10.2-2.6.19.jar) 
	UCHIJA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.0.2010.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.91' Renderer: 'GeForce GT 520M/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2013
	LWJGL: 2.9.4
	OpenGL: GeForce GT 520M/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.91, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Українська (Україна)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 361.91
	OpenGlRenderer: GeForce GT 520M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by chief-j** [comment]
[fml-client-latest.txt](https://github.com/Vectron/mapwriter/files/365484/fml-client-latest.txt)
[latest.txt](https://github.com/Vectron/mapwriter/files/365485/latest.txt)

**Comment by chief-j** [comment]
lates.log https://gist.github.com/chief-j/bef600b3992a4a70a10559224858f0c2 
fml-client-latest.log https://gist.github.com/chief-j/ac38f4fec5c5604fa99b731f14589437

**Comment by Vectron** [comment]
hmm it seems my fallback isnt realy a viable option....

i'll see if i can contact the dev of optifine maybe he has a awnser.

**Comment by Vectron** [comment]
disable fast rendering in optifine, this screws over almost every mod

**Comment by chief-j** [comment]
Thank you for the hint
