### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by ZeroAurora** [Vectron/mapwriter#61]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 17-7-9 下午9:53
Description: Initializing game

java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at mapwriter.util.Utils.allocateDirectIntBuffer(Utils.java:112)
	at mapwriter.util.Texture.<init>(Texture.java:54)
	at mapwriter.BlockColourGen.genBlockColours(BlockColourGen.java:97)
	at mapwriter.Mw.reloadBlockColours(Mw.java:289)
	at mapwriter.forge.EventHandler.onGuiOpenEvent(EventHandler.java:151)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventHandler_onGuiOpenEvent_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:931)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:530)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at mapwriter.util.Utils.allocateDirectIntBuffer(Utils.java:112)
	at mapwriter.util.Texture.<init>(Texture.java:54)
	at mapwriter.BlockColourGen.genBlockColours(BlockColourGen.java:97)
	at mapwriter.Mw.reloadBlockColours(Mw.java:289)
	at mapwriter.forge.EventHandler.onGuiOpenEvent(EventHandler.java:151)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventHandler_onGuiOpenEvent_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:931)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:530)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 300267408 bytes (286 MB) / 484442112 bytes (462 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E3 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.0-law.jar) 
	UCHIJA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJA	MapWriter{2.6.19} [MapWriter] (MapWriter-1.10.2-2.6.19.jar) 
	UCHIJA	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13417 Compatibility Profile Context 15.301.1901.0' Renderer: 'AMD Radeon HD 7500M/7600M Series'
	Launched Version: HMCL 2.7.8.33
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7500M/7600M Series GL version 4.5.13417 Compatibility Profile Context 15.301.1901.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.10.2-r4.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13417 Compatibility Profile Context 15.301.1901.0
	OpenGlRenderer: AMD Radeon HD 7500M/7600M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

**Comment by ZeroAurora** [comment]
Before adding this mod, my Minecraft can run well.
I have allocated 1G memory to Minecraft.
And,I'm a Chinese player,so I use Google Translate to submit this comment. :)

**Comment by Vectron** [comment]
all i can say is, try and give it more ram

**Comment by ZeroAurora** [comment]
Okay, after I allocated 1.5G of memory to Minecraft, it worked fine.
But I hope it can run under 768M of memory.
